[package]
name = "conjugation"
version = "0.1.0"
authors = ["statiolake <statiolake@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-igo = { git = "https://github.com/statiolake/typed-igo-rs" }
